"""Add All the Tables

Revision ID: 07a1fb6ba5d4
Revises: 
Create Date: 2025-09-29 17:38:00.138783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a1fb6ba5d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_id'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_user_name'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_index(op.f('ix_tbl_notes_id'), table_name='tbl_notes')
    op.drop_table('tbl_notes')
    op.drop_index(op.f('ix_tbl_outgoing_reports_id'), table_name='tbl_outgoing_reports')
    op.drop_table('tbl_outgoing_reports')
    op.drop_index(op.f('ix_tbl_warehouses_id'), table_name='tbl_warehouses')
    op.drop_table('tbl_warehouses')
    op.drop_index(op.f('ix_tbl_adjustment_spillage_id'), table_name='tbl_adjustment_spillage')
    op.drop_table('tbl_adjustment_spillage')
    op.drop_index(op.f('ix_tbl_adjustment_parent_id'), table_name='tbl_adjustment_parent')
    op.drop_table('tbl_adjustment_parent')
    op.drop_index(op.f('ix_tbl_raw_materials_id'), table_name='tbl_raw_materials')
    op.drop_table('tbl_raw_materials')
    op.drop_index(op.f('ix_tbl_status_id'), table_name='tbl_status')
    op.drop_table('tbl_status')
    op.drop_index(op.f('ix_tbl_stock_on_hand_id'), table_name='tbl_stock_on_hand')
    op.drop_table('tbl_stock_on_hand')
    op.drop_index(op.f('ix_tbl_product_kind_id'), table_name='tbl_product_kind')
    op.drop_table('tbl_product_kind')
    op.drop_index(op.f('ix_tbl_receiving_reports_id'), table_name='tbl_receiving_reports')
    op.drop_table('tbl_receiving_reports')
    op.drop_index(op.f('ix_tbl_held_forms_id'), table_name='tbl_held_forms')
    op.drop_table('tbl_held_forms')
    op.drop_index(op.f('ix_tbl_adjustment_correct_id'), table_name='tbl_adjustment_correct')
    op.drop_table('tbl_adjustment_correct')
    op.drop_index(op.f('ix_tbl_transfer_forms_id'), table_name='tbl_transfer_forms')
    op.drop_table('tbl_transfer_forms')
    op.drop_index(op.f('ix_tbl_preparation_forms_id'), table_name='tbl_preparation_forms')
    op.drop_table('tbl_preparation_forms')
    op.drop_index(op.f('ix_tbl2_preparation_forms_id'), table_name='tbl2_preparation_forms')
    op.drop_table('tbl2_preparation_forms')
    op.drop_table('rm_inventory_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rm_inventory_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('matcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('beg_inv', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('total_incoming', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('out_lab', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('out_despa', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('out_pulverized', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('out_purging', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('out_rrf', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('prod_used', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('ending_inv', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('loss', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('copy_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rm_inventory_report_pkey'))
    )
    op.create_table('tbl2_preparation_forms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('prod_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty_required', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('preparation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_prepared', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('qty_return', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl2_preparation_forms_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl2_preparation_forms_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl2_preparation_forms_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl2_preparation_forms_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl2_preparation_forms_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl2_preparation_forms_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl2_preparation_forms_pkey'))
    )
    op.create_index(op.f('ix_tbl2_preparation_forms_id'), 'tbl2_preparation_forms', ['id'], unique=True)
    op.create_table('tbl_preparation_forms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('preparation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_prepared', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('qty_return', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_adjusted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_preparation_forms_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_preparation_forms_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name='tbl_preparation_forms_rm_code_id_fkey'),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name='tbl_preparation_forms_status_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_preparation_forms_updated_by_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name='tbl_preparation_forms_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_preparation_forms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_preparation_forms_id'), 'tbl_preparation_forms', ['id'], unique=True)
    op.create_table('tbl_transfer_forms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transfer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_adjusted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_transfer_forms_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_transfer_forms_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['tbl_warehouses.id'], name='tbl_transfer_forms_from_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name='tbl_transfer_forms_rm_code_id_fkey'),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name='tbl_transfer_forms_status_id_fkey'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['tbl_warehouses.id'], name='tbl_transfer_forms_to_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_transfer_forms_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_transfer_forms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_transfer_forms_id'), 'tbl_transfer_forms', ['id'], unique=True)
    op.create_table('tbl_adjustment_correct',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incorrect_preparation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('incorrect_receiving_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('incorrect_outgoing_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('incorrect_transfer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('incorrect_change_status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('adjustment_parent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('from_warehouse_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_warehouse_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('current_status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('new_status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('qty_prepared', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('qty_return', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adjustment_parent_id'], ['tbl_adjustment_parent.id'], name=op.f('tbl_adjustment_correct_adjustment_parent_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_correct_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['current_status_id'], ['tbl_status.id'], name=op.f('tbl_adjustment_correct_current_status_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_correct_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_adjustment_correct_from_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['incorrect_change_status_id'], ['tbl_held_forms.id'], name=op.f('tbl_adjustment_correct_incorrect_change_status_id_fkey')),
    sa.ForeignKeyConstraint(['incorrect_outgoing_id'], ['tbl_outgoing_reports.id'], name=op.f('tbl_adjustment_correct_incorrect_outgoing_id_fkey')),
    sa.ForeignKeyConstraint(['incorrect_preparation_id'], ['tbl_preparation_forms.id'], name=op.f('tbl_adjustment_correct_incorrect_preparation_id_fkey')),
    sa.ForeignKeyConstraint(['incorrect_receiving_id'], ['tbl_receiving_reports.id'], name=op.f('tbl_adjustment_correct_incorrect_receiving_id_fkey')),
    sa.ForeignKeyConstraint(['incorrect_transfer_id'], ['tbl_transfer_forms.id'], name=op.f('tbl_adjustment_correct_incorrect_transfer_id_fkey')),
    sa.ForeignKeyConstraint(['new_status_id'], ['tbl_status.id'], name=op.f('tbl_adjustment_correct_new_status_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_adjustment_correct_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl_adjustment_correct_status_id_fkey')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_adjustment_correct_to_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_correct_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_adjustment_correct_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_adjustment_correct_pkey')),
    sa.UniqueConstraint('adjustment_parent_id', name=op.f('tbl_adjustment_correct_adjustment_parent_id_key'))
    )
    op.create_index(op.f('ix_tbl_adjustment_correct_id'), 'tbl_adjustment_correct', ['id'], unique=True)
    op.create_table('tbl_held_forms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('new_status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('change_status_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_adjusted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_held_forms_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['current_status_id'], ['tbl_status.id'], name=op.f('tbl_held_forms_current_status_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_held_forms_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['new_status_id'], ['tbl_status.id'], name=op.f('tbl_held_forms_new_status_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_held_forms_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_held_forms_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_held_forms_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_held_forms_pkey'))
    )
    op.create_index(op.f('ix_tbl_held_forms_id'), 'tbl_held_forms', ['id'], unique=True)
    op.create_table('tbl_receiving_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('receiving_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_adjusted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_receiving_reports_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_receiving_reports_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_receiving_reports_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl_receiving_reports_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_receiving_reports_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_receiving_reports_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_receiving_reports_pkey'))
    )
    op.create_index(op.f('ix_tbl_receiving_reports_id'), 'tbl_receiving_reports', ['id'], unique=True)
    op.create_table('tbl_product_kind',
    sa.Column('id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_product_kind_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_product_kind_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_product_kind_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_product_kind_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_product_kind_id'), 'tbl_product_kind', ['id'], unique=True)
    op.create_table('tbl_stock_on_hand',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rm_soh', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_imported', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_change_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('stock_recalculation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_stock_on_hand_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_stock_on_hand_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_stock_on_hand_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl_stock_on_hand_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_stock_on_hand_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_stock_on_hand_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_stock_on_hand_pkey')),
    sa.UniqueConstraint('rm_code_id', 'rm_soh', 'warehouse_id', 'stock_change_date', 'status_id', name=op.f('uix_rm_soh_warehouse_status'))
    )
    op.create_index(op.f('ix_tbl_stock_on_hand_id'), 'tbl_stock_on_hand', ['id'], unique=True)
    op.create_table('tbl_status',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_status_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_status_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_status_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_status_pkey'),
    sa.UniqueConstraint('name', name='tbl_status_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_status_id'), 'tbl_status', ['id'], unique=True)
    op.create_table('tbl_raw_materials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rm_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_raw_materials_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_raw_materials_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_raw_materials_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_raw_materials_pkey'),
    sa.UniqueConstraint('rm_code', name='tbl_raw_materials_rm_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_raw_materials_id'), 'tbl_raw_materials', ['id'], unique=True)
    op.create_table('tbl_adjustment_parent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('responsible_person', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('adjustment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('referenced_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_adjustment_parent_pkey'))
    )
    op.create_index(op.f('ix_tbl_adjustment_parent_id'), 'tbl_adjustment_parent', ['id'], unique=True)
    op.create_table('tbl_adjustment_spillage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reference_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('spillage_form_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('incident_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('responsible_person', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_spillage_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_spillage_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_adjustment_spillage_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl_adjustment_spillage_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_adjustment_spillage_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_adjustment_spillage_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_adjustment_spillage_pkey'))
    )
    op.create_index(op.f('ix_tbl_adjustment_spillage_id'), 'tbl_adjustment_spillage', ['id'], unique=True)
    op.create_table('tbl_warehouses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('wh_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('wh_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name='tbl_warehouses_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name='tbl_warehouses_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name='tbl_warehouses_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_warehouses_pkey'),
    sa.UniqueConstraint('wh_name', name='tbl_warehouses_wh_name_key'),
    sa.UniqueConstraint('wh_number', name='tbl_warehouses_wh_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_warehouses_id'), 'tbl_warehouses', ['id'], unique=True)
    op.create_table('tbl_outgoing_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rm_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ref_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('outgoing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_adjusted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_outgoing_reports_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_outgoing_reports_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['rm_code_id'], ['tbl_raw_materials.id'], name=op.f('tbl_outgoing_reports_rm_code_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['tbl_status.id'], name=op.f('tbl_outgoing_reports_status_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_outgoing_reports_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['tbl_warehouses.id'], name=op.f('tbl_outgoing_reports_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_outgoing_reports_pkey'))
    )
    op.create_index(op.f('ix_tbl_outgoing_reports_id'), 'tbl_outgoing_reports', ['id'], unique=True)
    op.create_table('tbl_notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lot_number', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('product_kind_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_change_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_computed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_notes_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['tbl_users.id'], name=op.f('tbl_notes_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['product_kind_id'], ['tbl_product_kind.id'], name=op.f('tbl_notes_product_kind_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_notes_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_notes_pkey'))
    )
    op.create_index(op.f('ix_tbl_notes_id'), 'tbl_notes', ['id'], unique=True)
    op.create_table('tbl_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_reguser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deavtivated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tbl_users.id'], name=op.f('tbl_users_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deavtivated_by_id'], ['tbl_users.id'], name=op.f('tbl_users_deavtivated_by_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['tbl_users.id'], name=op.f('tbl_users_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_users_pkey'))
    )
    op.create_index(op.f('ix_tbl_users_user_name'), 'tbl_users', ['user_name'], unique=True)
    op.create_index(op.f('ix_tbl_users_id'), 'tbl_users', ['id'], unique=True)
    # ### end Alembic commands ###
